/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fomoSol from "./Fomo.sol";
export type { fomoSol };
import type * as weekSol from "./Week.sol";
export type { weekSol };
import type * as abstract from "./abstract";
export type { abstract };
import type * as interface from "./interface";
export type { interface };
import type * as mock from "./mock";
export type { mock };
export type { CardNFT } from "./CardNFT";
export type { FOLToken } from "./FOLToken";
export type { Family } from "./Family";
export type { Home } from "./Home";
export type { Levels } from "./Levels";
export type { Migrations } from "./Migrations";
export type { Mine } from "./Mine";
export type { Nodes } from "./Nodes";
export type { Random } from "./Random";
