/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAssetPool,
  IAssetPoolInterface,
} from "../../../contracts/interface/IAssetPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "depositedAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sentAmount",
        type: "uint256",
      },
    ],
    name: "depositedDelegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAssetPool__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetPoolInterface {
    return new utils.Interface(_abi) as IAssetPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAssetPool {
    return new Contract(address, _abi, signerOrProvider) as IAssetPool;
  }
}
