/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IMine, IMineInterface } from "../../../contracts/interface/IMine";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "power",
        type: "uint256",
      },
    ],
    name: "addPowerDelegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "clearPowerDelegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMine__factory {
  static readonly abi = _abi;
  static createInterface(): IMineInterface {
    return new utils.Interface(_abi) as IMineInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IMine {
    return new Contract(address, _abi, signerOrProvider) as IMine;
  }
}
