/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRandom,
  IRandomInterface,
} from "../../../contracts/interface/IRandom";

const _abi = [
  {
    inputs: [],
    name: "seed",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "update",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRandom__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomInterface {
    return new utils.Interface(_abi) as IRandomInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandom {
    return new Contract(address, _abi, signerOrProvider) as IRandom;
  }
}
