version: "3"
services:
  # ipfs
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
  # postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: ganacheuser
      POSTGRES_PASSWORD: ganachepwd
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: -E UTF8 --locale=C
  # graph-node
  graph-node:
    image: graphprotocol/graph-node:v0.30.0
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
      - 8030:8030
      - 8040:8040
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: ganacheuser
      postgres_pass: ganachepwd
      postgres_db: graph-node
      ethereum: ganache:http://host.docker.internal:8545
      ipfs: "http://host.docker.internal:5001"
      GRAPH_LOG: info
