/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TranferEthWithCard,
  TranferEthWithCardInterface,
} from "../../../contracts/abstract/TranferEthWithCard";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "card",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class TranferEthWithCard__factory {
  static readonly abi = _abi;
  static createInterface(): TranferEthWithCardInterface {
    return new utils.Interface(_abi) as TranferEthWithCardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TranferEthWithCard {
    return new Contract(address, _abi, signerOrProvider) as TranferEthWithCard;
  }
}
