/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Achievement } from "./Achievement";
export type { PermissionControl } from "./PermissionControl";
export type { TranferEthWithCard } from "./TranferEthWithCard";
